### ISSUE TITLE
Ajouter un produit

### ISSUE THREAD

**Issue by cyrilGrandjean** [D34DPlayer/Projet-Dev-Web#1]
En tant que propriétaire du site,
je souhaite pouvoir ajouter un produit au site: le produit possède un nom, une description, un prix et une ou plusieurs photos.
pour pouvoir renouveler mon offre de produit.

**Comment by cyrilGrandjean** [comment]
### Condition de complétion:
obtenir un page dans le quel on peut ajouter un produit, se produit doit se rajouter dans la base de donnée à la suite de l'envoi du formulaire.

**Comment by D34DPlayer** [comment]
**Critères de complétion :**
- Via l'interface d'administration, le propriétaire de la boucherie doit être capable de : 
- Avoir accès à un formulaire demandant : le nom, la description, le prix, la réduction s'il y en a une et une série de photos.
- Ce formulaire va renvoyer ces informations à l'API sur la route "/products/add", qui retournera un code 201 si tout s'est bien passé ou un code erreur s'il y a eu un souci quelque part.
- En fonction du code réponse, le frontend saura ce qui a coincé et affichera le message approprié, si le problème vient d'un des inputs de l'utilisateur, le champ sera marqué comme invalide.
- Une fois un code 201 réçu, le produit tel qu'envoyé par le propriétaire se retrouvera sauvegardé dans la base de données.

**Objectif :**
L'objectif de cette US est de mettre une base pour le système de produits qui sera utilisé pour afficher le stock et l'offre de la boucherie/service traiteur et de permettre au propriétaire d'avoir le contrôle dessus.

**Prérequis :**
Pour que l'US soit complète à 100% il faudra qu'elle soit intégrée dans l'interface admin (#15)

**Maquettes visuelles :**
Formulaire :
![Maquette formulaire ajout produit](https://i.goopics.net/k8Zll.png)

**Champs :**

- nom (Nom) : text
- description (Description) : textarea
- prix (Prix) : number
- prix_promo (Prix en promotion) : number (optionnel)
- type_prix (Type de prix) : selection ["/kilo", "/unité"]
- display (Afficher le produit dans la liste) : checkbox
- photos (Photos du produit) : file multiple

**API :**
| methode | path | Description | Input | Output |
|:-------:|:----:|:-----------:|:-----:|:------:|
| POST | /products | Permet d'ajouter un produit à la liste | Product + Token admin | Product créé ou erreur |

**Librairies à utiliser :**
- Changement de la structure de la db => migrations => Alembic
- Pydantic pour définir les schémas input et output du Produit
- Le stockage des images doit être persistant, et l'accès doit être partagé entre le backend qui les reçoit et les enregistre et le frontend qui les affichera, pour ne pas devoir envoyer les images de l'un à l'autre à chaque fois.
Pour ce faire, un volume docker devra être partagé entre les deux containers et la db ne retiendra et l'api ne retournera que le chemin de l'image dans ses requêtes.
- Le stockage des images peut prendre un certain temps et donc il serait peut-être intéressant d'utiliser une Background Task de FastAPI pour s'en charger, une fois le reste effectué.

**Erreurs possibles :**
- Input du mauvais type, ou incomplet => Le frontend recevra comme réponse le champ qui a causé cette erreur et l'affichera à l'utilisateur.
- Une fois l'interface admin et le login en place, token invalide => redirection vers la page login.
- Toute autre erreur qui sera donc côté serveur => Message erreur au dessus du formulaire : "Une erreur est sourvenue, veuillez réessayer plus tard."

**Sous-tâches :**
- #38 Définir le schéma *Produit*, cf. [modèle UML](/D34DPlayer/Projet-Dev-Web/wiki/Diagramme-UML)
- #39 Définir le modèle *Produit*, cf. [modèle DB](/D34DPlayer/Projet-Dev-Web/wiki/Diagramme-DB)
- #39 Migrer la DB pour intégrer le nouveau modèle
- #41 Mettre en place un système pour stocker les photos des produits
- #40 Route API pour ajouter un produit, cf. [Organisation API](/D34DPlayer/Projet-Dev-Web/wiki/Organisation-API)
- #42 Formulaire frontend qui implémente l’interaction avec l'API pour l'ajout d'un produit
