### ISSUE TITLE
Visibilité produit

### ISSUE THREAD

**Issue by cyrilGrandjean** [D34DPlayer/Projet-Dev-Web#4]
En tant que propriétaire du site
je souhaite pouvoir sélectionner quels produits doivent être visibles sur le site
pour pouvoir afficher les produits disponibles.

**Comment by mwath** [comment]
### Critères de complétion:
Via l'interface d'administration, le propriétaire du site web doit pouvoir:
- Changer la visibilité d'un produit à l'aide d'un bouton.
- Lorsque celui-ci est appuyé, une requête PUT est envoyée à l'endpoint `/products/{id}/visibility`, `id` étant l'identifiant du produit.
- La requête retournera un code 200 une fois le produit modifié dans la base de donnée ou bien un code d'erreur suivit d'un message si une erreur est survenue.
- Si aucune erreur n'est survenue, le frontend changera l’icône de visibilité (voir maquettes). Dans le cas contraire, il affichera un message d'erreur.

### Objectif
L'objectif de cette US est de permettre au propriétaire du site de définir si un produit doit être visible dans la liste des produits.

### Prérequis
Pour que l'US soit complète, il faudra qu'elle soit intégrée dans l'interface admin (#15)

### Maquettes visuelles
Visible | Invisible
:-:|:-:
![Visible](https://user-images.githubusercontent.com/64019721/117081298-e87d4200-ad3f-11eb-9a02-ad6c32f88e2b.png) | ![Invisible](https://user-images.githubusercontent.com/64019721/117081480-3e51ea00-ad40-11eb-8453-86177ab5d1c4.png)

### API
Méthode | Endpoint |  Description | Input | Output
:-: | :-: | :-: | :-: | :-:
PUT | /products/{id}/visibility | Rends (in)visible le produit avec l'id fourni | id + Token admin + `{ visibility: boolean }` | Product mis à jour ou erreur
