### ISSUE TITLE
Système pour stocker les photos des produits

### ISSUE THREAD

**Issue by D34DPlayer** [D34DPlayer/Projet-Dev-Web#41]
Les photos ajoutées par l'utilisateur pour un produit doivent être enregistrées dans un dossier spécifique dans la partie statique (avec un volume docker lié pour persistance).

Pour faire le lien entre un produit (dans la base de données) et ce fichier, une nouvelle table est créée avec comme clé principale le nom du fichier (peut-être à modifier pour assurer l'unicité) et un clé étrangère pour faire référence au produit.

Pour que le frontend ait accès aux images, ce volume devra aussi être monté sur ce container.

**Comment by mwath** [comment]
Au lieu d'avoir une nouvelle table qui fait la relation entre un produit et ses images, pourquoi ne pas utiliser plus simplement le système de fichier ?
On peut facilement structurer les produits en dossiers pour éviter les conflits de noms de fichiers. De plus, il est possible d'utiliser l'url pour retrouver le fichier sur le disque avec un format tel que `/images/products/{id}/{filename}`.

Par exemple, prenons le produit suivant: 
```JSON
{
  "id": 42,
  "name": "Merguez",
  "photos": [],
  ...
}
```

Si on veut rajouter les images:
 - `merguez.jpg`
 - `merguez_cuites.jpg`

Celles-ci seront upload respectivement sur le disque aux emplacements:
 - `/images/products/42/merguez.jpg`
 - `/images/products/42/merguez_cuites.jpg`

Les fichiers seront alors disponibles aux urls:
 - https://boucherie.tk/images/products/42/merguez.jpg
 - https://boucherie.tk/images/products/42/merguez_cuites.jpg
